services:
  catty-app:
    image: ${APP_IMAGE}
    restart: unless-stopped
    ports:
      - "${APP_PORT}:8181"
    env_file:
      - .env
    depends_on:
      - catty_db

  catty_db:
    image: mariadb:10.11
    restart: unless-stopped
    ports:
      - "${DB_PORT}:3306"
    env_file:
      - .env
    volumes:
      - catty_db_data:/var/lib/mysql

volumes:
  catty_db_data:

