services:
  app:
    image: ghcr.io/andreypreobrazhenskiy/catty-reminders-app:${DEPLOY_REF}
    ports:
      - "8181:8181"
    environment:
      - DEPLOY_REF=${DEPLOY_REF}
    volumes:
      - ./config.json:/catty-reminders-app/config.json:ro
    depends_on:
      - db
    networks:
      - app-network
    pull_policy: always

  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mypass
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mypass
      - MYSQL_DATABASE=catty_reminders
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
