serverAddr = "course.prafdin.ru"
serverPort = 7000
auth.method = "token"
auth.token = "devops"

[[proxies]]
name = "hook-nepryakhin"
type = "http"
localPort = 8080
customDomains = ["webhook.nepryakhin.course.prafdin.ru"]

[[proxies]]
name = "app-nepryakhin"
type = "http"
localPort = 8181
customDomains = ["app.nepryakhin.course.prafdin.ru"]
