serverAddr = "course.prafdin.ru"
serverPort = 7000

auth.method = "token"
auth.token = "devops"

[[proxies]]
name = "app-kuzmin"
type = "http"
localIP = "127.0.0.1"
localPort = 8181
customDomains = ["app.kuzmin.course.prafdin.ru"]

[[proxies]]
name = "hook-kuzmin"
type = "http"
localIP = "127.0.0.1"
localPort = 8080
customDomains = ["webhook.kuzmin.course.prafdin.ru"]
