serverAddr = "course.prafdin.ru"
serverPort = 7000

auth.method = "token"
auth.token = "devops"

[[proxies]]
name = "hook-nikolaev"
type = "http"
localPort = 8080
customDomains = ["webhook.nikolaev.course.prafdin.ru"]

[[proxies]]
name = "app-nikolaev"
type = "http"
localPort = 8181
customDomains = ["app.nikolaev.course.prafdin.ru"]
