serverAddr = "course.prafdin.ru"
serverPort = 7000
auth.method = "token"
auth.token = "devops"

[[proxies]]
name = "app-zavadskiy"
type = "http"
localPort = 8181
customDomains = ["app.zavadskiy.course.prafdin.ru"]

[[proxies]]
name = "ssh-zavadskiy"
type = "tcp"
localPort = 22
remotePort = 3143
