serverAddr = "course.prafdin.ru"
serverPort = 7000
auth.method = "token"
auth.token = "devops"

[[proxies]]
name = "app-bisultanov"
type = "http"
localPort = 8181
customDomains = ["app.bisultanov.course.prafdin.ru"]

[[proxies]]
name = "ssh-bisultanov"
type = "tcp"
localPort = 22
remotePort = 3136
