name: CD Workflow
on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: course.prafdin.ru
          username: ilya
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 3120
          debug: true
            script_stop: true
          script: |
            cd ~/catty-reminders-app
            git fetch origin lab2
            git reset --hard origin/lab2
            
            # Установка зависимостей
            pip install -r requirements.txt
            
            # Убиваем старый процесс (если он есть)
            pkill -f "python3 main.py" || true
            
            # Запускаем приложение на порту 8181
            # Добавляем </dev/null, чтобы SSH сессия могла закрыться
            nohup python3 main.py --port 8181 </dev/null > log.txt 2>&1 &
            
            # Даем приложению 2 секунды завестись и проверяем, что процесс живой
            sleep 2
            ps aux | grep "python3 main.py" | grep -v grep
            echo "Deployment finished successfully"
